name: EpilepsyHat
version: 1.0.0
author: rkomonkey2
website: 
main: de.lualzockt.DiscoArmor.DiscoArmor

commands:
  epilepsyhat:
    description: epilepsy hat
    aliases: [eh]
    
    
permissions:
  eh.*:
    description: Gives access to all Epilepsy Hat commands.
    children:
      wh.toggle: true
      disocarmor.help: true
      discoarmor.info: true
      discoarmor.reload: true
      epilepsyhat.toggleothers: true
  epilepsyhat.toggle:
    description: Toggles your Epilepsy-Mode
  discoarmor.help:
    description: Permission to see the help
    default: true
  discoarmor.info:
    default: true
  discoarmor.toggleothers:
    description: Permission for toggling other players DiscoArmor mode
  
    
